
##create one product
PATCH http://localhost:5052/api/v1/products/e3c42cd6-aa50-4f7f-8448-002a15eacbe3
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI4M2M4NmZjMC00MjU0LTRkYmYtYTBmZS1mNGYxMDdiOGU1ZTMiLCJyb2xlIjoiQWRtaW4iLCJuYmYiOjE2OTIxMjE2MTEsImV4cCI6MTY5MjEyMjIxMSwiaWF0IjoxNjkyMTIxNjExLCJpc3MiOiJlY29tbWVyY2UtYmFja2VuZCJ9.qmoy_kUX9rC4-bbUrj__IN5fqb1XcInSLyMpdm1W7c8

{
  "title": "string",
  "descreption": "string",
  # "price": 110,
  "images": [
    {
      "createAt": "2023-08-15T17:23:36.978Z",
      "updatedAt": "2023-08-15T17:23:36.978Z",
      "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "link": "string"
    }
  ]
}


### login user
POST http://localhost:5052/api/v1/auth
Content-Type: application/json

{
  "email": "rich6@gmail.com",
  "password": "123"
}



# ##create one admin
# POST http://localhost:5052/api/v1/users/admin
# Content-Type: application/json

# {
#   "firstName": "Rich",
#   "lastName": "Lee",
#   "email": "rich6@gmail.com",
#   "avatar": "rich",
#   "password": "123"
# }



### get all users
GET  http://localhost:5052/api/v1/products/
Content-Type: application/json



# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI4M2M4NmZjMC00MjU0LTRkYmYtYTBmZS1mNGYxMDdiOGU1ZTMiLCJyb2xlIjoiQWRtaW4iLCJuYmYiOjE2OTIwNDEwNTMsImV4cCI6MTY5MjA0MTY1MywiaWF0IjoxNjkyMDQxMDUzLCJpc3MiOiJlY29tbWVyY2UtYmFja2VuZCJ9.Vjf588ycr1FU3ygsDAEFgnY3TH6KeQb3pqynG1ouN0E



"Default" : "server=backend.postgres.database.azure.com; port=5432; username=rich; password=backend@12345; database=backend"