
# ##create one admin
# POST http://localhost:5052/api/v1/users/admin
# Content-Type: application/json

# {
#   "firstName": "Rich",
#   "lastName": "Lee",
#   "email": "rich6@gmail.com",
#   "avatar": "rich",
#   "password": "123"
# }


### login user
POST http://localhost:5052/api/v1/auth
Content-Type: application/json

{
  "email": "rich6@gmail.com",
  "password": "123"
}



# ##create one admin
# POST http://localhost:5052/api/v1/users/admin
# Content-Type: application/json

# {
#   "firstName": "Rich",
#   "lastName": "Lee",
#   "email": "rich6@gmail.com",
#   "avatar": "rich",
#   "password": "123"
# }



### get all users
GET http://localhost:5052/api/v1/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI4M2M4NmZjMC00MjU0LTRkYmYtYTBmZS1mNGYxMDdiOGU1ZTMiLCJyb2xlIjoiQWRtaW4iLCJuYmYiOjE2OTIwNDEwNTMsImV4cCI6MTY5MjA0MTY1MywiaWF0IjoxNjkyMDQxMDUzLCJpc3MiOiJlY29tbWVyY2UtYmFja2VuZCJ9.Vjf588ycr1FU3ygsDAEFgnY3TH6KeQb3pqynG1ouN0E